/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface CloudflareEnv ./cloudflare-env.d.ts` (hash: 82a38fff698b983dcab65adc3de9c782)
declare namespace Cloudflare {
  interface Env {
    KV: KVNamespace
    WARPCAST_BASE_URL: string
    WARPCAST_ACCESS_TOKEN: string
    WARPCAST_API_KEY: string
    LILNOUNS_SUBGRAPH_URL: string
    SITE_BASE_URL: string
  }
}
interface CloudflareEnv extends Cloudflare.Env {}
