// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bbdbf9f51f19a3a0dd92214ed2eb44da)
declare namespace Cloudflare {
  interface Env {
    KV: KVNamespace
    WARPCAST_BASE_URL: 'https://api.warpcast.com'
    WARPCAST_ACCESS_TOKEN: string
    WARPCAST_API_KEY: string
    LILNOUNS_SUBGRAPH_URL: string
    SITE_BASE_URL: string
  }
}
interface Env extends Cloudflare.Env {}
