// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 7ec0fd2b9b6c6c0138837fbc3a3d40a1)
declare namespace Cloudflare {
  interface Env {
    KV: KVNamespace
    WARPCAST_BASE_URL: string
    WARPCAST_ACCESS_TOKEN: string
    WARPCAST_API_KEY: string
    LILNOUNS_SUBGRAPH_URL: string
    SITE_BASE_URL: string
  }
}
interface Env extends Cloudflare.Env {}
