// Generated by Wrangler on Mon Sep 09 2024 08:57:25 GMT+0400 (Gulf Standard Time)
// by running `wrangler types`

interface Env {
  CHAIN_ID: 1
  CONTRACT_AUCTION: '0xA2587b1e2626904c8575640512b987Bd3d3B592D'
  ETHEREUM_BLOCKS_SUBGRAPH_URL: string
  ALCHEMY_API_KEY: string
  WALLET_MNEMONIC: string
  DB: D1Database
  QUEUE: Queue
}
